# Generated by Django 5.1 on 2024-08-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='confirmPassword',
        ),
    ]
